on:
  push:
    branches:
      - main
name: Deploy ftp on push
jobs:
  ftp-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.host_ftp }}
          username: ${{ secrets.user_ftp }}
          password: ${{ secrets.password_ftp }}
          server-dir: files/
          
